### ISSUE TITLE
Cannot POST /search/metadata

### ISSUE THREAD

**Issue by davidpcrd** [ArnaudCrl/immich-automated-selfie-timelapse#14]
When i try to create a video, i've got this error

```
immich-selfie-timelapse  |  * Running on http://127.0.0.1:5000
immich-selfie-timelapse  |  * Running on http://172.26.0.2:5000
immich-selfie-timelapse  | 08:54:21 - werkzeug - INFO - Press CTRL+C to quit
immich-selfie-timelapse  | 08:54:21 - werkzeug - INFO - 213.55.220.228 - - [15/Apr/2025 08:54:21] "GET / HTTP/1.1" 200 -
immich-selfie-timelapse  | 08:54:21 - werkzeug - INFO - 213.55.220.228 - - [15/Apr/2025 08:54:21] "GET /check-connection HTTP/1.1" 200 -
immich-selfie-timelapse  | 08:54:38 - werkzeug - INFO - 213.55.220.228 - - [15/Apr/2025 08:54:38] "POST / HTTP/1.1" 200 -
immich-selfie-timelapse  | 08:54:38 - immich_api - INFO - Error fetching page 1: 404 - {"message":"Cannot POST /search/metadata","error":"Not Found","statusCode":404}
immich-selfie-timelapse  | 08:54:38 - image_processing - INFO - Found 0 assets containing the person.
immich-selfie-timelapse  | 08:54:38 - INFO - Found 0 assets containing the person.
0it [00:00, ?it/s]lapse  | 
immich-selfie-timelapse  | 08:54:38 - image_processing - INFO - Finished processing. 0 images saved out of 0 assets.
immich-selfie-timelapse  | 08:54:38 - compile_timelapse - ERROR - No image files found in folder
immich-selfie-timelapse  | 08:54:38 - werkzeug - INFO - 213.55.220.228 - - [15/Apr/2025 08:54:38] "GET /check-connection HTTP/1.1" 200 -
```

But when i check with the same api-key et personIds on python i have a lot of results
```python
import requests
import json

base = "..."
api_key = "..."
url = base+"/api/search/person?name=David"

payload = {}
headers = {
  'Accept': 'application/json',
  'x-api-key': f'{api_key}'
}

response = requests.request("GET", url, headers=headers, data=payload)
print(response.text)


url = base+"/api/search/metadata"

payload = json.dumps({
  "personIds": [
    "a92b35aa-8a41-421c-b738-3ff1cff3185f"
  ],
})
headers = {
  'Content-Type': 'application/json',
  'Accept': 'application/json',
  'x-api-key': f'{api_key}'
}


response = requests.request("POST", url, headers=headers, data=payload)
print(response.text) # lots of pictures
```

**Comment by davidpcrd** [comment]
Found the problem. My docker compose was

```
services:
  immich-selfie-timelapse:
    image: arnaudcayrol/immich-selfie-timelapse
    container_name: immich-selfie-timelapse
    ports:
      - "5095:5000"
    volumes:
      - ./immich_selfie_timelapse:/app/output
    environment:
      - IMMICH_API_KEY=...
      - IMMICH_BASE_URL=https://url/
```

and the ui said connection successful BUT there is a error in the dockerfile, it's should be
`- IMMICH_BASE_URL=https://url/api` instead.

Maybe do a check to see if the url is correct
