### ISSUE TITLE
immich-selfie-timelapse exited with code 132

### ISSUE THREAD

**Issue by l4rm4nd** [ArnaudCrl/immich-automated-selfie-timelapse#6]
The docker container does not provide much debugging information.

Once spawned, it just crashes:

````
[+] Running 1/1
 ✔ Container immich-selfie-timelapse  Recreated                                                                                                                                                                                                                                                              0.1s
Attaching to immich-selfie-timelapse
immich-selfie-timelapse exited with code 0
immich-selfie-timelapse exited with code 132
immich-selfie-timelapse exited with code 132
````

Here my compose:

````
services:

  immich-selfie-timelapse:
    image: arnaudcayrol/immich-selfie-timelapse
    container_name: immich-selfie-timelapse
    restart: unless-stopped
    expose:
      - 5000
    volumes:
      - ./immich_selfie_timelapse:/app/output
    environment:
      - IMMICH_API_KEY=redacted
      - IMMICH_BASE_URL=https://immich.example.com/api
    labels:
      - traefik.enable=true
      - traefik.http.routers.timelapse.rule=Host(`timelapse.example.com`)
      - traefik.http.services.timelapse.loadbalancer.server.port=5000
      # Optional part for traefik middlewares
      - traefik.http.routers.timelapse.middlewares=local-ipwhitelist@file
````

**Comment by groenska** [comment]
Same Problem on a Synology-Server (DS220+). Even with a minimal setup, the container crashes instantly. 

```
  immich-selfie-timelapse:
    image: arnaudcayrol/immich-selfie-timelapse
    container_name: immich-selfie-timelapse
    ports:
      - "5030:5000"
#    volumes:
#      - /volume1/photo/selfie-timelapse:/app/output
    environment:
      - IMMICH_API_KEY=
      - IMMICH_BASE_URL=http://IP:2283/api
```
